fyodorov example tests
javaGuruBY/rpaS2 pull request #118
Opened 2021-01-26 11:23 UTC by youRaFyodorov

2021-01-26 22:48 UTC, LiudmilaZhdanok requested changes
watch the new video in Alumni from the stand-up on how to delete workspace.xml

2021-01-28 14:44 UTC, olgaz-skiba approved these changes

2021-01-28 18:00 UTC, integratorBY approved these changes
lgfm. but change some code

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/pom.xml
> +                                            <minimum>0.0</minimum>
set 0.6

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/main/java/by/jrr/mytest/bean/Dog.java
> +package by.jrr.mytest.bean;
change package name

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/main/java/by/jrr/mytest/bean/Dog.java
> +    int age;
use private

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/main/java/by/jrr/mytest/service/DogService.java
> +    Dog dog;
use private

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/main/java/by/jrr/mytest/service/DogService.java
> +    }
use method .conact()

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/main/java/by/jrr/mytest/service/DogService.java
> +        return convertedPrice;
avoid to use magic string

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/main/java/by/jrr/mytest/service/DogServiceUtil.java
> +        return dog.getName () + " BARK!";
magic string . psfs - short key

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/main/java/by/jrr/mytest/service/DogServiceUtil.java
> +        return dog.getName () + " BARK!";
create class with name "DogLanguage" and set magic string into this

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/test/java/by/jrr/mytest/service/DogServiceTest.java
> +import static org.junit.Assert.*;
import only static method

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/test/java/by/jrr/mytest/service/DogServiceTest.java
> +import static org.junit.Assert.*;
dont use *

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/test/java/by/jrr/mytest/service/DogServiceTest.java
> +        Dog dog = new Dog ();
use var

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/test/java/by/jrr/mytest/service/DogServiceTest.java
> +        DogService dogService = new DogService(dog);
use var

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/test/java/by/jrr/mytest/service/DogServiceTest.java
> +        double expected = 762; //762
remove comment

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/test/java/by/jrr/mytest/service/DogServiceTest.java
> +        Dog dog = new Dog ();
create private method to create `var dog = new Dog()`

2021-01-28 18:00 UTC, integratorBY commented on homework/java/fyodorov/lecture2/task1/src/test/java/by/jrr/mytest/service/DogServiceTest.java
> +        double expected = 2956.56; //3048
delete comment

2021-01-28 18:29 UTC, javaGuruBY approved these changes
minor comments

2021-01-28 18:29 UTC, javaGuruBY commented on homework/java/fyodorov/lecture2/task1/src/main/java/by/jrr/mytest/service/DogService.java
> +        return dog.getName () + " BARK!";
You can create class DogLanguage with static fields like this:
```
public class DogLanguage() {
    public static final String BARKING = "BARK!";
}
```

Than in code you can address like this:
```
public String bark() {
        return String.format("%s %s", dog.getName(), DogLanguage.BARKING);
}
```

2021-01-28 20:09 UTC, LiudmilaZhdanok approved these changes
lgfm

2021-01-28 20:12 UTC, merged