Suhorutchenko hw1 t1 t2
javaGuruBY/rpaS2 pull request #66
Opened 2021-01-19 22:33 UTC by mykoIa

task completed

2021-01-19 22:40 UTC, lember3 submitted a review, later dismissed

2021-01-20 10:53 UTC, Yur4eg1 requested changes
see notes

2021-01-20 10:53 UTC, Yur4eg1 commented on homework/english/sukhorutchenko/lecture1/vocabulary.md
> +It is always necessary to plug in git it is convenient
You have to divide the sentenсes for right structure:
It is always necessary to plug in _a_ git .It is convenient

2021-01-20 10:53 UTC, Yur4eg1 commented on homework/english/sukhorutchenko/lecture1/vocabulary.md
> +Enable a new fuch today
fuch -?

2021-01-20 15:10 UTC, mykoIa reviewed
string 45 and 33

2021-01-20 15:11 UTC, mykoIa commented on homework/english/sukhorutchenko/lecture1/vocabulary.md
> +It is always necessary to plug in git it is convenient
ok

2021-01-20 15:12 UTC, mykoIa commented on homework/english/sukhorutchenko/lecture1/vocabulary.md
> +Enable a new fuch today
changed

2021-01-20 15:16 UTC, Eliseyhom submitted a review, later dismissed
lgfm

2021-01-21 09:33 UTC, goldenas18 commented on homework/english/sukhorutchenko/lecture1/grammar.md
> +2. What do you do after school?
We are not going to school today. 2. What are you doing after school?

2021-01-21 09:38 UTC, goldenas18 commented on homework/english/sukhorutchenko/lecture1/vocabulary.md
> +It doesn't display the screen
maybe "on the screen"?

2021-01-21 14:04 UTC, mykoIa reviewed
grammar: str 31, 32
vocabulary: 30

2021-01-21 14:19 UTC, goldenas18 commented on homework/english/sukhorutchenko/lecture1/vocabulary.md
> +Today I'm doing a debugging program
"Today I'm going to debug the program" or "Today I'm debugging the program"

2021-01-21 14:25 UTC, goldenas18 commented on homework/english/sukhorutchenko/lecture1/grammar.md
> +21. Mike does not wear a tie today.
isn't wearing

2021-01-21 14:40 UTC, goldenas18 approved these changes

2021-01-21 14:40 UTC, mykoIa reviewed
grammar: str 25
vocabulary: 15

2021-01-21 14:48 UTC, goldenas18 approved these changes
seems great)

2021-01-21 14:55 UTC, Yur4eg1 approved these changes

2021-01-21 16:55 UTC, lember3 approved these changes

2021-01-21 16:56 UTC, merged