2nd task has been done
javaGuruBY/rpaS2 pull request #83
Opened 2021-01-20 14:59 UTC by VolhaZh

2021-01-20 15:29 UTC, Alex99905 approved these changes

2021-01-20 16:36 UTC, breackinumber requested changes
Good, but with some problems.

2021-01-21 08:02 UTC, olgaz-skiba approved these changes

2021-01-21 17:03 UTC, breackinumber commented on homework/english/Volha_Zharava/lecture1/task2.md
> +My account connect to the main repository
**is connected**

2021-01-21 17:04 UTC, breackinumber commented on homework/english/Volha_Zharava/lecture1/task2.md
> +I want develop a chatbot while learning this course
want **to** develop

2021-01-21 17:05 UTC, breackinumber commented on homework/english/Volha_Zharava/lecture1/task2.md
> +I disconnect this zoom session now
I've been dissconnected from this zoom session

2021-01-21 17:06 UTC, breackinumber commented on homework/english/Volha_Zharava/lecture1/task2.md
> +Result of running programm display at a terminal window
program**m** - program

2021-01-21 17:07 UTC, breackinumber commented on homework/english/Volha_Zharava/lecture1/task2.md
> +Sonar verify programm code
program**m** - program

2021-01-21 17:08 UTC, breackinumber requested changes
Comments were added

2021-01-21 17:11 UTC, VolhaZh commented on homework/english/Volha_Zharava/lecture1/task2.md
> +Result of running programm display at a terminal window
agree
thnx

2021-01-21 17:12 UTC, VolhaZh commented on homework/english/Volha_Zharava/lecture1/task2.md
> +Sonar verify programm code
ok

2021-01-21 17:33 UTC, Alex99905 approved these changes

2021-01-21 17:33 UTC, breackinumber approved these changes

2021-01-21 17:33 UTC, merged

2021-01-21 17:33 UTC, Alex99905 approved these changes

2021-01-21 17:34 UTC, Alex99905 approved these changes

2021-01-21 17:34 UTC, breackinumber reviewed
All fixed

2021-01-21 17:35 UTC, Alex99905 approved these changes

2021-01-21 17:37 UTC, Alex99905 approved these changes